### ISSUE TITLE
register err

### ISSUE THREAD

**Issue by Lagikna** [feihoo87/QuLab#1]
NameError                                 Traceback (most recent call last)
<ipython-input-52-d181a950ed9b> in <module>()
      5 _bootstrap._connect_db()
      6 
----> 7 register()

D:\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\lib\site-packages\lab\admin.py in register()
     19 def register():
     20     username, password, email, fullname = getRegisterInfo()
---> 21     user =User(name=username, email=email, fullname=fullname)
     22     user.password = password
     23     user.save()

NameError: name 'User' is not defined

**Comment by feihoo87** [comment]
Fixed
