### ISSUE TITLE
driver 33120A 导入后出现错误

### ISSUE THREAD

**Issue by Lagikna** [feihoo87/QuLab#12]
name|	version|	modules|	time
----|----|----|----
Agilent_PNA|	1|	lab.drivers.Agilent_PNA|	2018-03-19 13:22:55.071428
Agilent_PSG_SignalGenerator|	1|	lab.drivers.Agilent_PSG_SignalGenerator|	2018-03-19 13:25:37.115696
DPO4104B|	1|	lab.drivers.DPO4104B|	2018-03-19 13:25:57.240847
IT6302|	1|	lab.drivers.IT6302|	2018-03-19 13:26:18.088040
SR620|	1|	lab.drivers.SR620|	2018-03-19 13:26:45.833626
Tek_AWG|	1|	lab.drivers.Tek_AWG|	2018-03-19 13:26:57.792310
driversÙ20A|	1|	Error! Module for driver not set|	N/A

最后一行

**Comment by feihoo87** [comment]
这个 Driver 你是怎么添加的？

**Comment by Lagikna** [comment]
跟其他的添加方式一样
```py
from lab import admin

admin.uploadDriver('B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\Lib\site-packages\lab\drivers\33120A.py')
```
采集卡是这样添加吗？
```py
admin.uploadDriver('B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\Lib\site-packages\lab\drivers\AlazarTech_Digitizer')
```

**Comment by Lagikna** [comment]
采集卡怎么添加到Instruments?

**Comment by feihoo87** [comment]
很显然是路径分隔符惹的祸，windows 下的路径分隔符`\`要小心对待。要么用双反斜杠，要么在字符串前面加`r`。你现在要先用数据库管理软件把那个带乱码的 driver 删掉。然后运行
```python
from lab import admin

admin.uploadDriver('B:\\WinPython-64bit-3.6.3.0Qt5\\python-3.6.3.amd64\\Lib\\site-packages\\lab\\drivers\\33120A.py')
admin.uploadDriver('B:\\WinPython-64bit-3.6.3.0Qt5\\python-3.6.3.amd64\\Lib\\site-packages\\lab\\drivers\\AlazarTech_Digitizer')
```

**Comment by Lagikna** [comment]
正常了！
ATS9870怎么加到仪器列表里？

**Comment by feihoo87** [comment]
```python
setInstrument("ATS1", "10.122.7.18", "ATS9870::SYSTEM1::1::INSTR", "AlazarTech_Digitizer")
```
我刚把`setInstrument()`移到`admin`里了。
