### ISSUE TITLE
listDrivers,listInstrument

### ISSUE THREAD

**Issue by Lagikna** [feihoo87/QuLab#8]
listDrivers()
listDrivers()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-9b4b39d767dc> in <module>()
----> 1 listDrivers()

B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\_bootstrap.py in listDrivers()
    141 def listDrivers():
    142     ret = _schema.Driver.objects()
--> 143     ui.list_drivers(ret)
    144 
    145 def listInstruments():

B:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\lib\site-packages\lab\ui\__init__.py in list_drivers(drivers)
     47     for driver in drivers:
     48         module = driver.module
---> 49         table.append('%s|%s|%s|%s' % (driver.name, driver.version, module.fullname, module.created_time))
     50         for sub_module in module.modules:
     51             table.append('%s|%s|%s|%s' % ('', '', sub_module.fullname, sub_module.created_time))

AttributeError: 'NoneType' object has no attribute 'fullname'

listInstruments()
| name | host | address | driver | |:----|:----|:----|:----|

**Comment by Lagikna** [comment]
仪器列举不出来啊

**Comment by feihoo87** [comment]
贴代码时用 Markdown，不然很多东西被转译了没法看。

**Comment by Lagikna** [comment]
# 怎么添加仪器到服务器？

列出来的没有仪器

**Comment by feihoo87** [comment]
Check out the new version and use `lab.setInstruemt()`
