### ISSUE TITLE
can't import setInstrument

### ISSUE THREAD

**Issue by Lagikna** [feihoo87/QuLab#9]
'''python
from lab._bootstrap import listApps,listDrivers,listInstruments,setInstrument
listApps()
'''
ImportError: cannot import name 'setInstrument'

**Comment by Lagikna** [comment]
代码里instrument写错了

**Comment by Lagikna** [comment]
改了还是导入不成功

**Comment by feihoo87** [comment]
```python
import lab
lab.login()
lab.listInstruments()
```

**Comment by Lagikna** [comment]
需要重启JupyterNotebook就好了

**Comment by Lagikna** [comment]
lab.__init__文件里面没有导入list XX这些项目，需要添加

**Comment by feihoo87** [comment]
已经提交了，你得更新一下你的库。
